export enum UserRole {
  OWNER = 'OWNER',
  MANAGER = 'MANAGER',
  ADVISOR = 'ADVISOR',
  TECHNICIAN = 'TECHNICIAN',
  STOCK = 'STOCK',
  CUSTOMER = 'CUSTOMER'
}

export enum Permission {
  REPAIR_CREATE = 'REPAIR_CREATE',
  REPAIR_READ = 'REPAIR_READ',
  REPAIR_UPDATE = 'REPAIR_UPDATE',
  INVENTORY_MANAGE = 'INVENTORY_MANAGE',
  PARTS_RESERVE = 'PARTS_RESERVE',
  PARTS_CONSUME = 'PARTS_CONSUME',
  TIMELOG = 'TIMELOG',
  PHOTOS_UPLOAD = 'PHOTOS_UPLOAD',
  RECEIPT_MANAGE = 'RECEIPT_MANAGE',
  NOTIFICATION_SEND = 'NOTIFICATION_SEND',
  USER_MANAGE = 'USER_MANAGE',
  REPORT_VIEW = 'REPORT_VIEW',
  SETTINGS_EDIT = 'SETTINGS_EDIT'
}
